name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 'run pipeline'
        uses: codefresh-io/codefresh-pip-runner-action@master
        env:
          PIPELINE_NAME: 'codefresh-pipeline'
          TRIGGER_NAME: 'codefresh-trigger'
          CF_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        id: run-pipeline
