name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: 'run pipeline'
        uses: ./
        env:
          PIPELINE_NAME: 'codefresh-pipeline'
          TRIGGER_NAME: 'codefresh-trigger'
          CF_API_KEY_NON_SECRET: 5d51a3377ebed0d5707bfedc.794887e1c6b7a0ed9e0153ac5def6a74
        id: run-pipeline
