name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
#       - name: Checkout
#         uses: actions/checkout@master

      - name: 'run pipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v5
        env:
          PIPELINE_NAME: 'codefresh-pipeline'
          TRIGGER_NAME: 'codefresh-trigger'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline
